import { useApp } from '../../context/AppContext'

export default function ExecBriefModal() {
    const { showExecBrief, setShowExecBrief } = useApp()
    if (!showExecBrief) return null

    return (
        <div className="modal-overlay" onClick={() => setShowExecBrief(false)}>
            <div className="modal exec-brief-modal" onClick={e => e.stopPropagation()}>
                <div className="modal-header">
                    <div>
                        <div className="modal-title">Executive Brief</div>
                        <div className="modal-sub">Wed, 25 Mar 2026 · Generated by MExI</div>
                    </div>
                    <button className="modal-close" onClick={() => setShowExecBrief(false)}>✕</button>
                </div>
                <div className="modal-body">
                    <div className="eb-section">
                        <div className="eb-section-title">🔴 Critical </div>
                        <p className="eb-text">
                            The business is under significant operational stress this week. On-Time Delivery has collapsed to <strong>58.3%</strong> against a 95% target, with 170 orders late across 6 customer accounts. Total revenue at risk stands at <strong>₹924L</strong>.
                        </p>
                    </div>
                    <div className="eb-section">
                        <div className="eb-section-title">⚠️ Top 3 Risks</div>
                        <ol className="eb-list">
                            <li><strong>OTD Collapse (₹247L overdue)</strong> — Vendor A missed 4 consecutive deliveries. Bonfiglioli account at escalation risk.</li>
                            <li><strong>Production Failure (₹424L at risk)</strong> — VTL-04 down, night shift uncovered, 38 orders past due.</li>
                            <li><strong>Supply Failure (₹180L risk)</strong> — No alternate vendor qualified. 14 orders will be starved in 5 days.</li>
                        </ol>
                    </div>
                    <div className="eb-section">
                        <div className="eb-section-title">💰 Financial Summary</div>
                        <div className="eb-kpis">
                            <div className="eb-kpi"><span className="eb-kpi-val red">₹924L</span><span className="eb-kpi-label">Revenue at Risk</span></div>
                            <div className="eb-kpi"><span className="eb-kpi-val orange">₹77L</span><span className="eb-kpi-label">Capital Locked</span></div>
                            <div className="eb-kpi"><span className="eb-kpi-val orange">1.4%</span><span className="eb-kpi-label">Margin Impact</span></div>
                            <div className="eb-kpi"><span className="eb-kpi-val red">58.3%</span><span className="eb-kpi-label">OTD</span></div>
                        </div>
                    </div>
                    <div className="eb-section">
                        <div className="eb-section-title">✅ Immediate Actions Required</div>
                        <ol className="eb-list">
                            <li>Escalate Vendor A SLA and initiate emergency alternate vendor qualification</li>
                            <li>Approve emergency maintenance budget for VTL-04 and fleet PM backlog</li>
                            <li>Schedule executive call with Bonfiglioli this week</li>
                            <li>Arrange contract operators for night shift coverage</li>
                        </ol>
                    </div>
                </div>
                <div className="modal-footer">
                    <button className="btn-cancel" onClick={() => setShowExecBrief(false)}>Close</button>
                    <button className="btn-save">Download PDF</button>
                </div>
            </div>
        </div>
    )
}
