/**
 * All Signal Engine routes under `/api/v1` (matches FastAPI router in Mexi-Endpoint `routes.py`).
 * Total: 47 route registrations in this router (Swagger path count may differ slightly; use this as the contract checklist).
 */
export const SIGNAL_ENGINE_ENDPOINTS = [
  { method: 'GET', path: '/bootstrap' },
  { method: 'GET', path: '/tenant' },
  { method: 'GET', path: '/data-sync/status' },
  { method: 'GET', path: '/me' },
  { method: 'PATCH', path: '/me' },
  { method: 'GET', path: '/me/preferences' },
  { method: 'PATCH', path: '/me/preferences' },
  { method: 'GET', path: '/preferences/scope' },
  { method: 'GET', path: '/signals' },
  { method: 'GET', path: '/signals/display-order' },
  { method: 'POST', path: '/signals/{signal_id}/run' },
  { method: 'POST', path: '/signals/evaluate' },
  { method: 'GET', path: '/signals/{signal_id}/what' },
  { method: 'GET', path: '/signals/{signal_id}/why' },
  { method: 'GET', path: '/signals/{signal_id}/impact' },
  { method: 'GET', path: '/signals/{signal_id}/actions' },
  { method: 'POST', path: '/signals/{signal_id}/ask' },
  { method: 'POST', path: '/signals/{signal_id}/actions/{idx}/assign' },
  { method: 'POST', path: '/signals/{signal_id}/actions/{idx}/run-agent' },
  { method: 'GET', path: '/signals/heatmap/all' },
  { method: 'GET', path: '/signals/heatmap/production' },
  { method: 'GET', path: '/signals/heatmap/supply-chain' },
  { method: 'GET', path: '/signals/heatmap/vendor' },
  { method: 'GET', path: '/signals/heatmap/demand-otd' },
  { method: 'GET', path: '/signals/heatmap/inventory' },
  { method: 'GET', path: '/signals/heatmap/quality' },
  { method: 'GET', path: '/signals/heatmap/maintenance' },
  { method: 'GET', path: '/signals/heatmap/planning' },
  { method: 'GET', path: '/signals/heatmap/marketing-sales' },
  { method: 'GET', path: '/biz-impact/cards' },
  { method: 'GET', path: '/risks/changed' },
  { method: 'GET', path: '/reports/executive-brief' },
  { method: 'GET', path: '/reports/executive-brief/overlay' },
  { method: 'GET', path: '/ask-mexi/suggested-prompts' },
  { method: 'GET', path: '/ask-mexi/conversations' },
  { method: 'POST', path: '/ask-mexi/conversations' },
  { method: 'GET', path: '/ask-mexi/conversations/{id}/messages' },
  { method: 'POST', path: '/ask-mexi/conversations/{id}/messages' },
  { method: 'POST', path: '/ask-mexi/last-context' },
  { method: 'GET', path: '/me/watchlist' },
  { method: 'PUT', path: '/me/watchlist' },
  { method: 'POST', path: '/me/watchlist/items' },
  { method: 'GET', path: '/entities/search' },
  { method: 'GET', path: '/dashboard/risk-exposure' },
  { method: 'GET', path: '/dashboard/brief-highlights' },
  { method: 'GET', path: '/health' },
  { method: 'GET', path: '/version' },
];
