import React, { useState } from 'react';

export function AllSignalsOverlay({ isOpen, onClose, roleData, SIGNALS, openPanel }) {
  const [filter, setFilter] = useState('all');

  if (!isOpen) return null;

  const allSigs = (roleData?.sigOrder || []).filter(id => SIGNALS[id] && !id.startsWith('func_'));
  const critCount = allSigs.filter(id => SIGNALS[id]?.sev === 'r').length;

  const filteredSigs = filter === 'all' ? allSigs : allSigs.filter(id => SIGNALS[id] && SIGNALS[id].sev === filter);

  return (
    <div className="all-signals-overlay open" onClick={onClose}>
      <div className="asp-card" onClick={e => e.stopPropagation()}>
        <div className="asp-hdr">
          <div className="asp-hdr-left">
            <div className="asp-title">All Priority Signals</div>
            <div className="asp-subtitle">{allSigs.length} signals · {critCount} critical</div>
          </div>
          <div className="asp-close" onClick={onClose}>✕</div>
        </div>
        <div className="asp-filters">
          <div className={`asp-filter ${filter === 'all' ? 'active' : ''}`} onClick={() => setFilter('all')}>All</div>
          <div className={`asp-filter ${filter === 'r' ? 'active' : ''}`} onClick={() => setFilter('r')}>Critical</div>
          <div className={`asp-filter ${filter === 'a' ? 'active' : ''}`} onClick={() => setFilter('a')}>Warning</div>
        </div>
        <div className="asp-body" id="asp-list">
          {filteredSigs.length > 0 ? filteredSigs.map((id, idx) => {
            const s = SIGNALS[id];
            const sevColor = s.sev === 'r' ? 'var(--critical)' : 'var(--warn)';
            const sevLabel = s.sev === 'r' ? 'Critical' : 'Warning';
            // Global rank is index in allSigs+1
            const globalRank = allSigs.indexOf(id) + 1;

            return (
              <div key={id} className="asp-row" onClick={() => { onClose(); openPanel(id); }}>
                <div className="asp-rank">#{globalRank}</div>
                <div className="asp-dot" style={{ background: sevColor }}></div>
                <div className="asp-info">
                  <div className="asp-name">{s.name}</div>
                  <div className="asp-proc">{s.proc}</div>
                </div>
                <div className="asp-sev" style={{ color: sevColor }}>{sevLabel}</div>
                <div className="asp-impact">{s.impact}</div>
                <div className="asp-arrow">↗</div>
              </div>
            );
          }) : (
            <div style={{ padding: '28px', textAlign: 'center', fontFamily: 'var(--f-body)', color: 'var(--ink-4)', fontSize: '13px' }}>No signals in this category</div>
          )}
        </div>
      </div>
    </div>
  );
}

export function BriefOverlay({ isOpen, onClose, roleData }) {
  if (!isOpen || !roleData) return null;

  return (
    <div className="settings-overlay open" onClick={onClose}>
      <div className="settings-card exec-brief-modal" onClick={e => e.stopPropagation()}>
        <div className="settings-hdr">
          <div>
            <div className="settings-title">Executive Brief</div>
            <div className="modal-sub">Wed, 25 Mar 2026 · Generated by MExI</div>
          </div>
          <div className="settings-close" onClick={onClose}>✕</div>
        </div>
        <div className="settings-body eb-body">

          <div className="eb-section">
            <div className="eb-section-title">🔴 Critical</div>
            <p className="eb-text">The business is under significant operational stress this week. On-Time Delivery has collapsed to <strong>58.3%</strong> against a 95% target, with 170 orders late across 6 customer accounts. Total revenue at risk stands at <strong>₹924L</strong>.</p>
          </div>

          <div className="eb-section">
            <div className="eb-section-title">⚠️ Top 3 Risks</div>
            <ol className="eb-list">
              <li><strong>OTD Collapse (₹247L overdue)</strong> — Vendor A missed 4 consecutive deliveries. Bonfiglioli account at escalation risk.</li>
              <li><strong>Production Failure (₹424L at risk)</strong> — VTL-04 down, night shift uncovered, 38 orders past due.</li>
              <li><strong>Supply Failure (₹180L risk)</strong> — No alternate vendor qualified. 14 orders will be starved in 5 days.</li>
            </ol>
          </div>

          <div className="eb-section">
            <div className="eb-section-title">💰 Financial Summary</div>
            <div className="eb-kpis">
              <div className="eb-kpi"><span className="eb-kpi-val red">₹924L</span><span className="eb-kpi-label">Revenue at Risk</span></div>
              <div className="eb-kpi"><span className="eb-kpi-val orange">₹77L</span><span className="eb-kpi-label">Capital Locked</span></div>
              <div className="eb-kpi"><span className="eb-kpi-val orange">1.4%</span><span className="eb-kpi-label">Margin Impact</span></div>
              <div className="eb-kpi"><span className="eb-kpi-val red">58.3%</span><span className="eb-kpi-label">OTD</span></div>
            </div>
          </div>

          <div className="eb-section">
            <div className="eb-section-title">✅ Immediate Actions Required</div>
            <ol className="eb-list">
              <li>Escalate Vendor A SLA and initiate emergency alternate vendor qualification</li>
              <li>Approve emergency maintenance budget for VTL-04 and fleet PM backlog</li>
              <li>Schedule executive call with Bonfiglioli this week</li>
              <li>Arrange contract operators for night shift coverage</li>
            </ol>
          </div>

          <div style={{ fontFamily: 'var(--f-mono)', fontSize: '8.5px', color: 'var(--ink-4)', textAlign: 'center', marginTop: '10px', paddingTop: '10px', borderTop: '1px solid var(--bd)' }}>
            Generated by MExI EBIA + FVLA engines · Data refreshed 08:14 · All figures from Veejei source data
          </div>
        </div>
        <div className="pref-footer">
          <div className="pref-cancel" onClick={onClose}>Close</div>
          <div className="pref-save">Download PDF</div>
        </div>
      </div>
    </div>
  );
}

export function SettingsOverlay({ isOpen, onClose, showToast }) {
  const [whatsappEnabled, setWhatsappEnabled] = useState(false);
  const [priorityData, setPriorityData] = useState({ revenue: false, cost: true, operations: true, quality: false });
  const [sensitivity, setSensitivity] = useState('1');

  if (!isOpen) return null;

  const togglePriority = (key) => {
    setPriorityData(prev => {
      const activeCount = Object.values(prev).filter(Boolean).length;
      if (!prev[key] && activeCount >= 3) {
        showToast('Max 3 priorities allowed');
        return prev;
      }
      return { ...prev, [key]: !prev[key] };
    });
  };

  const handleSave = () => {
    showToast('Preferences saved');
    onClose();
  };

  const sensLabels = ['Low — Major issues only', 'Medium — Important issues', 'High — Early signals'];

  return (
    <div className="settings-overlay open" onClick={onClose}>
      <div className="settings-card pref-card" onClick={e => e.stopPropagation()}>
        <div className="settings-hdr pref-hdr">
          <div>
            <div className="settings-title">Preferences</div>
            <div className="pref-summary">
              MExI will monitor Cost and Operations risks across All Plants and notify you instantly for Critical issues via Email.
            </div>
          </div>
          <div className="settings-close" onClick={onClose}>✕</div>
        </div>
        <div className="settings-body pref-body">
          <div className="pref-section">
            <div className="pref-sec-title">Business Focus</div>
            <div className="pref-sec-helper">What should MExI prioritise?</div>
            <div className="pref-field-label">Priority <span className="pref-field-hint">Pick up to 3</span></div>
            <div className="pref-chips">
              <div className={`pref-chip ${priorityData.revenue ? 'active' : ''}`} onClick={() => togglePriority('revenue')}>Revenue</div>
              <div className={`pref-chip ${priorityData.cost ? 'active' : ''}`} onClick={() => togglePriority('cost')}>Cost</div>
              <div className={`pref-chip ${priorityData.operations ? 'active' : ''}`} onClick={() => togglePriority('operations')}>Operations</div>
              <div className={`pref-chip ${priorityData.quality ? 'active' : ''}`} onClick={() => togglePriority('quality')}>Quality</div>
            </div>
            <div className="pref-field-label" style={{ marginTop: '14px' }}>Scope</div>
            <select className="pref-select">
              <option value="all">All Plants</option>
              <option value="a">Plant A</option>
              <option value="b">Plant B</option>
              <option value="x">Region X</option>
            </select>
          </div>

          <div className="pref-section">
            <div className="pref-sec-title">Alerts</div>
            <div className="pref-sec-helper">When and how should MExI notify you?</div>
            <div className="pref-field-label">Alert Types</div>
            <div className="pref-toggles">
              <div className="pref-toggle-row">
                <span className="pref-toggle-label">Financial Risks</span>
                <div className="toggle on"></div>
              </div>
              <div className="pref-toggle-row">
                <span className="pref-toggle-label">Operational Issues</span>
                <div className="toggle on"></div>
              </div>
              <div className="pref-toggle-row">
                <span className="pref-toggle-label">Quality Issues</span>
                <div className="toggle"></div>
              </div>
            </div>

            <div className="pref-field-label" style={{ marginTop: '14px' }}>Severity</div>
            <div className="pref-radios">
              <label className="pref-radio-row"><input type="radio" name="severity" value="critical" defaultChecked /><span>Critical Only</span></label>
              <label className="pref-radio-row"><input type="radio" name="severity" value="high" /><span>Critical + High</span></label>
            </div>

            <div className="pref-field-label" style={{ marginTop: '14px' }}>Delivery</div>
            <div className="pref-seg">
              <div className="pref-seg-opt active">Instant</div>
              <div className="pref-seg-opt">Daily Summary</div>
            </div>

            <div className="pref-field-label" style={{ marginTop: '14px' }}>Channel</div>
            <div className="pref-checks">
              <label className="pref-check-row"><input type="checkbox" defaultChecked /><span>Email</span></label>
              <label className="pref-check-row"><input type="checkbox" checked={whatsappEnabled} onChange={(e) => setWhatsappEnabled(e.target.checked)} /><span>WhatsApp</span></label>
            </div>
            {whatsappEnabled && (
              <div className="pref-info-text">Messages will be sent to your registered mobile number</div>
            )}
          </div>

          <div className="pref-section" style={{ borderBottom: 'none' }}>
            <div className="pref-sec-title">Sensitivity</div>
            <div className="pref-sec-helper">How early should MExI flag issues?</div>
            <div className="pref-slider-wrap">
              <input type="range" min="0" max="2" step="1" value={sensitivity} className="pref-slider" onChange={(e) => setSensitivity(e.target.value)} />
              <div className="pref-slider-labels">
                <span>Low<br /><small>Major issues only</small></span>
                <span style={{ textAlign: 'center' }}>Medium<br /><small>Important issues</small></span>
                <span style={{ textAlign: 'right' }}>High<br /><small>Early signals</small></span>
              </div>
              <div className="pref-slider-value">{sensLabels[parseInt(sensitivity)]}</div>
            </div>
          </div>
        </div>
        <div className="pref-footer">
          <div className="pref-cancel" onClick={onClose}>Cancel</div>
          <div className="pref-save" onClick={handleSave}>Save Preferences</div>
        </div>
      </div>
    </div>
  );
}
